# This configuration file is for the **development** setup.
# For a production example please refer to setup/docker-compose.yml.
version: '3.2'
services:
  app:
    build: .
    volumes:
      - .:/app
